name: build and publish nuget

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: MSBuild Setup
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Nuget Setup
      uses: nuget/setup-nuget@v1.0.5
    - name: Validate Gradle wrapper
      working-directory: src/AndroidStudio
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build AAR with Gradle
      working-directory: src/AndroidStudio
      run: ./gradlew bundleReleaseAar
    - name: Nuget Restore
      run: nuget restore src/iFIT.ExoPlayer.sln
    - name: Build
      run: msbuild src/iFIT.ExoPlayer/iFIT.ExoPlayer.csproj /property:Configuration=Release /warnaserror
#     - name: Publish
#       uses: dansiegel/publish-nuget@v1.01
#       with:
#         filename: 'src/JavaGl.Obj/bin/Release/JavaGl.Obj.*.nupkg'
#         apiKey: ${{ secrets.NUGET_API_KEY }}
